### ISSUE TITLE
Incorrectly limits resources

### ISSUE THREAD

**Issue by underhax** [oulfr/php#3]
Hello. Continued testing of php.
cgroup v2
CPU Quota 60-80%
CPU Quota Period 100ms -1s
If you set 100ms, it limits for some time correctly, but after a while the process "gets stuck" and the limitation becomes 5-10% of CPU.
If you set, for example, 1s, it immediately limits within 5-10%.

**Comment by codebyoul** [comment]
Hello,

Thank you for raising this issue. The rule is that if you want 60% of CPU usage, the formula is  60000/x*100 = 60% . In this case, the time period must be set to 100ms. However, 100ms is the minimum, and 1 second is the maximum period.

If you’re not seeing the expected behavior, it could mean that another process is being prioritized, or there may be a bug in the cgroup implementation. Ask cgroup teams may will have better explanation.

**Comment by codebyoul** [comment]
Note also that you need to use 100ms to have the accurate result, what do you mean cpu stuck after a while can you describe your test scenario?

**Comment by underhax** [comment]
This is the settings window in hestia cp v1.9.0~beta1 
<img width="663" alt="Снимок экрана 2024-12-20 в 23 34 16" src="https://github.com/user-attachments/assets/814b103c-ee0e-485f-95bf-f6a90dfa7be2" />
There is clearly no limit from 100ms to 1s, it is assumed that there can be more than 1 second and less than 100ms.
Even on the test php from this repository, if you set 1sec, the limit is always within 10% and it doesn't matter if you set more than 10% in the limits.

About some time: I started the service on a working server, set 100ms and for sites with wordpress woocommerce and just worpress set the maximum 75% and 60% CPU respectively. Some time these restrictions work 30 minutes - 1 hour (time is random), but then regardless of the settings restrictions stick at 5-10% and after that when working in the admin panel pages take a long time to load. It is worth restarting this service and php-fpm service, the work of restrictions are restored for some time.

So in this form the solution is not working for me unfortunately.

**Comment by codebyoul** [comment]
Read carefully what I write, if you need the accurate percent of cpu always use 100ms then if you made change in admin panel you need to run :

sudo kill -HUP $(cat /var/run/process-slice-manager.pid)

**Comment by underhax** [comment]
> sudo kill -HUP $(cat /var/run/process-slice-manager.pid)

Of course I did it all, just like the instructions.
And this:
```
sudo kill -HUP $(cat /var/run/process-slice-manager.pid)
```
And even so:
Stopped the service, with process-slice-manager.pid no longer there either
```
systemctl stop process-slice-manager.service
```
Changed the package settings, then started the service again

Perhaps you yourself or someone else can test your solution. I have tested it, I wrote down what else is the problem.

**Comment by codebyoul** [comment]
Why do you need to get 60% of cpu if the task can be done just with 0.2% of cpu your testing scenarios is not clear ? Explain how do you test

**Comment by underhax** [comment]
If not limited, sometimes php-fpm for woocommerce sites start to consume too many resources - it comes to 100+ % per 1 process, and there are many such processes, many sites too.

Therefore, if there is a maximum limitation of 60-75% for each of the processes, it is quite enough for comfortable work. Most often, sites themselves consume much less resources.

On average for loaded woocommerce sites short-term consumption is about 20-30%

I don't need a constant load of 60 or 75, I need it to stay within those limits, but also not hard limit it to 5-10% when 20-30 is needed

**Comment by codebyoul** [comment]
I’m not sure I understood your response clearly, as each reply seems to contradict the previous one. If you think the script is not correct you can correct it and send me a pull request. Sorry

**Comment by codebyoul** [comment]
If you have a clear, step-by-step scenario to reproduce an issue, feel free to open a ticket, and I’d be happy to take a look. Unfortunately, as much as I’d love to, I can’t read minds—yet :)
